### ISSUE TITLE
Disable debugging features

### ISSUE THREAD

**Issue by pentschev** [conda-forge/ucx-split-feedstock#110]
### Comment:

I'm curious if there's a reason why the UCX package is not doing release builds, currently [`ucx/configure`](https://github.com/conda-forge/ucx-split-feedstock/blob/65e8a970247c2e8179aa2ad62e6454e2541ea5df/recipe/install_ucx.sh#L14) is used, but the UCX repo provides a [`ucx/contrib/configure-release`](https://github.com/openucx/ucx/blob/master/contrib/configure-release) file that disables some features that are generally better suited for a debug build, which may also be somewhat detrimental to performance.

Is there a reason to keep building in the way it is currently build, or should we consider doing release builds as described above? I'm happy to submit a patch for that, unless someone has a reason why we should keep the build as it currently is.

**Comment by leofang** [comment]
I am sure @jakirkham would know better the reason, to me it's simply my lack of knowledge of the proper way to build UCX. I'd say PRs are definitely welcomed.

**Comment by pentschev** [comment]
Thanks Leo for the quick reply, I opened https://github.com/conda-forge/ucx-split-feedstock/pull/111 to address that.

**Comment by jakirkham** [comment]
Yeah changing this seems reasonable.

The main issue is to make sure UCX isn't changing ABI compatibility of the libraries on rebuild (this can happen as debug libraries sometimes use different symbols). If it does, we might need to think harder about this change to minimize breakage of existing binaries (or coordinate it with a new release).

Most `configure` scripts have an `--enable-debug` flag that gets passed to enable debug mode. One can pass `--disable-debug` mode to be explicit, but that would already be the default. Had assumed this was the case with UCX, but didn't realize something non-standard was done here (maybe there is a reason for this?). Asking if this can be improve on in issue ( https://github.com/openucx/ucx/issues/8642 ).

**Comment by jakirkham** [comment]
Digging deeper into `configure-release`, it appears it passes [`--disable-debug` along with a few other flags related to logging and assertions back to `configure`]( https://github.com/openucx/ucx/blob/5e32bd070d25203be4a17860ba473d026334d544/contrib/configure-release#L15-L18 ).

**Comment by pentschev** [comment]
I'm not sure whether ABI is changed or not to be honest. But I agree with you, maybe waiting for the next UCX release is more appropriate to reduce breakage. What would be the best way to ensure we don't forget about that when the new release is out?

**Comment by jakirkham** [comment]
Maybe we should do this as part of 1.14.0?
