### ISSUE TITLE
UCX: Support CUDA 12

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/ucx-split-feedstock#116]
Depends on the new CUDA packages ( https://github.com/conda-forge/staged-recipes/issues/21382 )

**Comment by pentschev** [comment]
Please note this depends on https://github.com/openucx/ucx/pull/8763 which has not made its way into v1.14.0, I've asked if it can be backported for the v1.14.1 release.

**Comment by jakirkham** [comment]
Thanks Peter! 🙏

Is there an issue tracking this backport request?

**Comment by pentschev** [comment]
Yes, there is https://github.com/openucx/ucx/issues/8936 and https://github.com/openucx/ucx/pull/8938 is the PR backporting the fix into the v1.14.x branch. As per the discussion there, we should get RCs for 1.14.1 including CUDA 12 support in about a week.

**Comment by jakirkham** [comment]
Earlier this week, the UCX version [1.14.1 release]( https://github.com/openucx/ucx/releases/tag/v1.14.1 ) was made

This was in turn packaged here with PR ( https://github.com/conda-forge/ucx-split-feedstock/pull/124 )

The CUDA 12 PR ( https://github.com/conda-forge/ucx-split-feedstock/pull/117 ) merged in these changes as well

So the issues noted above, should now be addressed
