### ISSUE TITLE
Build w/OpenMP?

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/ucx-split-feedstock#119]
Noticed in recent builds that UCX looks for OpenMP support, which we currently are not building with.

Looking at UCX source it seems OpenMP is mainly used for testing/benchmarking and not in the library (though could be wrong about this). If that's true, there probably isn't a need to build against OpenMP.

Still wanted to raise the question in case I've missed something. Do we want to build with OpenMP? Would that be useful?

**Comment by leofang** [comment]
cc: @pentschev for vis

**Comment by pentschev** [comment]
I think you're right, it seems to be used only for tests and perf tools. I believe that, at least on the RAPIDS side, we've never built against OpenMP, so we're probably ok with that unless people in the community have a need for it.

**Comment by jakirkham** [comment]
Closing since it sounds like we don't need this

**Comment by jakirkham** [comment]
Looks like this was getting used unintentionally without the dependency. Tried to disable it, but that surfaced an upstream build issue: https://github.com/openucx/ucx/issues/9848

At this point it seems easier to enable OpenMP and make it an explicit dependency (so we at least know that it is being used). Doing that in PR: https://github.com/conda-forge/ucx-split-feedstock/pull/173

That said, am hoping we can disable it in the future as there can be certain challenges with OpenMP that would be best avoided (especially as this isn't necessarily providing value to the user)
