### ISSUE TITLE
valid run constraint?

### ISSUE THREAD

**Issue by beckermr** [conda-forge/ucx-split-feedstock#120]
Is this line 

```
cudatoolkit {{ cuda_compiler_version }}  # [cuda_compiler_version not in ("None", "11.2")]
```

a valid run constraint or do we need

```
cudatoolkit =={{ cuda_compiler_version }}.*  # [cuda_compiler_version not in ("None", "11.2")]
```

I am seeing mamba fail weirdly on this in some cases.

**Comment by beckermr** [comment]
mamba says

```
Encountered problems while solving:
  - package ucx-1.14.0-h0aa22dc_1 has constraint cudatoolkit 10.2 conflicting with cudatoolkit-10.2.89-h8f6ccaa_6
```

**Comment by pentschev** [comment]
I can confirm what you're seeing with:

```
$ mamba create -n cuda102 python=3.8 cudatoolkit=10.2 ucx=1.14
...
Encountered problems while solving:
  - package ucx-1.14.0-h0aa22dc_1 has constraint cudatoolkit 10.2 conflicting with cudatoolkit-10.2.89-h6bb024c_0
```

And for CUDA 11.1, which seems to be an [explicit build of the UCX package](https://github.com/conda-forge/ucx-split-feedstock/blob/main/.ci_support/linux_64_c_compiler_version10cdt_namecos7cuda_compiler_version11.1cxx_compiler_version10.yaml#L14), shows that it's also pinning to 10.2 as well:

```
$ mamba create -n cuda111 python=3.8 cudatoolkit=11.1 ucx=1.14
...
Encountered problems while solving:
  - package ucx-1.14.0-h0aa22dc_1 has constraint cudatoolkit 10.2 conflicting with cudatoolkit-11.1.1-h6406543_8
```

It seems that pinning to `cudatoolkit =={{ cuda_compiler_version }}.*` would resolve this, but I'm honestly not very experienced, also not sure if it would resolve the 11.1 build either. @jakirkham maybe you could shed some light on this?

**Comment by beckermr** [comment]
We'll need to patch old packages too.

**Comment by jakirkham** [comment]
Yep we can do that. Think there are only a couple of these since this change was relatively recent

**Comment by jakirkham** [comment]
Reopening for the repodata patch

**Comment by jakirkham** [comment]
If you have time to open the repodata patch, Matt, that would be helpful. No worries if not

I may be able to get to it later, but probably not right away

**Comment by jakirkham** [comment]
Started the repodata patch in PR ( https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/445 )

**Comment by beckermr** [comment]
Thank you. I left one comment.

**Comment by leofang** [comment]
Thanks to you all for catching/fixing it!
