### ISSUE TITLE
RFC: rdma-core version pinning

### ISSUE THREAD

**Issue by pentschev** [conda-forge/ucx-split-feedstock#143]
### Comment:

Based on previous discussions we were under the false impression that rdma-core 28.x was necessary to support all of MOFED 5.x. That understanding was incorrect, even though rdma-core 28.x should still support MOFED 5.x moving to the latest rdma-core (currentl 48.0) should be preferred instead, and the newest rdma-core version will still support MOFED 5.x. The newest rdma-core should also support all modern kernel versions, so this should not be a blocker for most users either.

With the above said, we can make a choice here as to what versions we should pin UCX to, just earlier today I [released rdma-core=48.0](https://github.com/conda-forge/rdma-core-feedstock/pull/8), it seems that we need to build UCX against the rdma-core version that contains all features we want/need, or in other words, if we build against the newest rdma-core we should support all features that UCX can utilize from rdma-core. However, we are still capable of running against newer rdma-core core versions, so do we want to pin UCX builds tightly to the current major version or do we want to have a loose pin to support newer rdma-core versions?

Advantages of pinning to `rdma-core>=48.0`:

- Does not force us to rebuild immediately against new rdma-core versions;
- Permits users who need a specific UCX version to upgrade to a newer rdma-core runtime.

Disadvantages:

- We can't guarantee that compatibility will be forever valid;
  - We may potentially want to define a maximum version (maybe arbitrarily define 3 or 5 major versions above?);
- Slightly more complex to maintain (needs to keep the [version to build against in CBC](https://github.com/conda-forge/ucx-split-feedstock/blob/main/recipe/conda_build_config.yaml#L1-L2), and add the pins we support to [run requirements](https://github.com/conda-forge/ucx-split-feedstock/blob/main/recipe/meta.yaml#L42)).

With the above said, I'd like to ask all people who care about InfiniBand/rdma-core support to comment on what sounds like the best approach to follow here, so please let me know if you have strong opinions about this. If we have no comments or strong opinions I will propose we move ahead with merging https://github.com/conda-forge/ucx-split-feedstock/pull/142 which will implicitly pin to `rdma-core>=48,<49` at runtime.

cc @jakirkham @kkraus14 @SeyedMir as you are some of the usual suspects and users on rdma-core matters.

**Comment by pentschev** [comment]
cc @quasiben for awareness.

**Comment by jakirkham** [comment]
cc @jgunthorpe @yosefe

**Comment by jakirkham** [comment]
If we go down this road, think we should add `rdma-core` to `conda-forge-pinning` ( as we did with `ucx`: https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/2847 ). This will allow upgrades of `rdma-core` to be handled with migrations and also ensure it is pinned consistently throughout `conda-forge`

**Comment by leofang** [comment]
Not entirely sure what's at stake here, but thinking out loud: if we build against a matrix of rdma-core (using say cbc.yaml), and add the latest to cf-pinning, would it be ok?

**Comment by kkraus14** [comment]
+1 to adding rdma-core to conda-forge pinning.

As far as allowing it to float forward at runtime, if it becomes later incompatible we could always address that with repodata patches as needed. Given the nature of UCX, it's not uncommon for users to need to stay on a bit older of versions and if we tightly pin rdma-core users will likely end up in annoying situations where they can't have an older version of UCX with newer versions of other packages due to the tight pinning.

**Comment by pentschev** [comment]
> This will allow upgrades of `rdma-core` to be handled with migrations and also ensure it is pinned consistently throughout `conda-forge`

Could you please clarify what "pinned consistently throughout `conda-forge`" means in `conda-forge`? Does it mean all new packages will be pinned to that version? I'm asking to understand what is the connection to Keith's suggestion below:

> As far as allowing it to float forward at runtime, if it becomes later incompatible we could always address that with repodata patches as needed.

How would `conda-forge` migrations handle building UCX with a specific version (say `48.0`) and letting it float forward (say `>=48.0`, no upper cap)?

**Comment by pentschev** [comment]
> Not entirely sure what's at stake here, but thinking out loud: if we build against a matrix of rdma-core (using say cbc.yaml), and add the latest to cf-pinning, would it be ok?

It would be ok, but we don't need that. It should be sufficient for us to build with the minimum rdma-core version we want to support and leaving without an upper cap. So one approach we could take is whenever there's a new major UCX release we build it with the latest `rdma-core` and leave it without an upper cap. E.g., say `rdma-core=50.0` is the latest release when `ucx=1.16.0` comes out, we could simply build `ucx=1.16.x` (1.16 with all its minor releases) build in conda-forge with `rdma-core=50.0` but leave the runtime pin uncapped to `rdma-core>=50.0`, and that should suffice supporting new versions.

**Comment by kkraus14** [comment]
> How would `conda-forge` migrations handle building UCX with a specific version (say `48.0`) and letting it float forward (say `>=48.0`, no upper cap)?

Lets say we add rdma-core to the conda-forge pinning at `48.0`, this would give us UCX `1.15.0` and rdma-core `48.0` in the conda-forge pinning. Any packages that depend on rdma-core will get version `48.0` at build time, as well as UCX `1.15.0` at build time. The run time pinnings of those packages are controlled by the run exports in their respective recipes.

Given there isn't necessarily 100% ABI compatibility for rdma-core, the run export for it may be to pin to the built major version. Say UCX handles this gracefully at runtime, we can always ignore the run export of rdma-core in the UCX feedstock and express our own runtime constraint along the lines of `rdma-core >=${RDMA_CORE_BUILD_VERSION}`. Then if there's an incompatible change introduced in say `RDMA_CORE_BUILD_VERSION + 5`, we could submit a repodata patch for the affected UCX builds that changes it to `rdma-core >=${RDMA_CORE_BUILD_VERSION},<${RDMA_CORE_BUILD_VERSION + 5}`.

**Comment by pentschev** [comment]
Thanks Keith for the thorough explanation. Based on your reply I've submitted https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/5017 to add `rdma-core` to the global pinnings. Besides that, I've also [added `rdma-core>=48` to the UCX recipe](https://github.com/conda-forge/ucx-split-feedstock/pull/142/commits/eb2bd9a4b214c709322795aa0e92349d48da1244).

Some things that aren't clear to me yet:

1. Do we need to add a `max_pin` to [`rdma-core`'s recipe](https://github.com/conda-forge/rdma-core-feedstock/blob/b617c8a772a849dd5e0b4026f4b56ca221941bce/recipe/meta.yaml#L18)? If we do, I imagine we want `max_pin="x.x"`, just like UCX utilizes, could you confirm that?
2. To this day I remain confused about `run`/`run_exports`/`run_constrained`, could you confirm if we want to add `rdma-core` to `run_exports` as done via [this commit](https://github.com/conda-forge/ucx-split-feedstock/pull/142/commits/eb2bd9a4b214c709322795aa0e92349d48da1244), or if we should move it to `run`/`run_constrained` instead?
3. Do we still need a [`conda_build_config.yaml` file](https://github.com/conda-forge/ucx-split-feedstock/blob/eb2bd9a4b214c709322795aa0e92349d48da1244/recipe/conda_build_config.yaml) to include the `rdma-core` pin, or is that now satisfied given we're moving it to a global pinning? IOW, can we remove that file completely now from the UCX recipe?

Thanks again for the help on getting this right, admittedly, conda packaging is still mostly a big black box to me. 😅

**Comment by pentschev** [comment]
Ok, I now understand the [global pinning is actually a key name, and not the package name](https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/5017/commits/c9a9f40261a6ce0552c720a8d1fcf6855061dc9a). Given that, I think the answer to item 3 above is that we should remove `conda_build_config.yaml` and instead change the pinning in `host` section to `rdma-core ={{ rdma_core }}`, but please correct me if I'm wrong here as well.

Also, the `run`/`run_exports`/`run_constrained` (still not sure where `rdma-core` should go) probably should then add `rdma-core >={{ rdma_core}}`, but again, please correct me if I'm wrong.

**Comment by kkraus14** [comment]
> Given that, I think the answer to item 3 above is that we should remove `conda_build_config.yaml` and instead change the pinning in `host` section to `rdma-core ={{ rdma_core }}`, but please correct me if I'm wrong here as well.

Correct, other than I think the `rdma_core` key will automatically get mapped to `rdma-core` so you shouldn't need to add the `={{ rdma_core }}`.

> 1. Do we need to add a `max_pin` to [`rdma-core`'s recipe](https://github.com/conda-forge/rdma-core-feedstock/blob/b617c8a772a849dd5e0b4026f4b56ca221941bce/recipe/meta.yaml#L18)? If we do, I imagine we want `max_pin="x.x"`, just like UCX utilizes, could you confirm that?

Correct, adding a `max_pin` is what we want. Using `x.x` will pin it to the minor version, so for UCX 1.15.0 it would yield a `run` requirement of `>=1.15.0,<1.16.0a0`. For UCX 1.15.1 it would yield `>=1.15.1,<1.16.0a0`. If rdma-core guarantees ABI stability within a major version then we could use `max_pin="x"` instead which would yield `>=48.0,<49.0a0`.

> 2\. To this day I remain confused about `run`/`run_exports`/`run_constrained`, could you confirm if we want to add `rdma-core` to `run_exports` as done via [this commit](https://github.com/conda-forge/ucx-split-feedstock/pull/142/commits/eb2bd9a4b214c709322795aa0e92349d48da1244), or if we should move it to `run`/`run_constrained` instead?

`run` is the runtime requirements of a package. Meaning that if a user installs that package, everything in the `run` section of the recipe will need to be satisfied in order to successfully install the package. `run_exports` allows packages to automatically add themselves to the `run` section with versioning constraints if they're used at build time (typically in the `host` section of a recipe). I.E. if someone has `ucx` in the `host` section, assuming v1.15.0, because they're linking against it during build, it will use the `run_exports` with the `x.x` max pin to yield a `run` section entry of `ucx >=1.15.0,<1.16.0a0`. `run_constrained` is generally for handling optional dependencies, i.e. "**If** this package is installed, it needs to follow these versioning constraints".

**Comment by pentschev** [comment]
Thanks @kkraus14 for another detailed response. I'm [adding `max_pin` based on your comments to rdma-core](https://github.com/conda-forge/rdma-core-feedstock/pull/9). If I understood everything correctly, on the UCX side we should:

1. Remove `conda_build_config.yaml`;
2. Use `rdma-core` with no extra constraints in the `host` section; and
3. Add `rdma-core >= {{ rdma_core }}` (here we need the `{{ rdma_core }}` key because of the local `>=` constraint) to the `run` section.

If this is correct, then all should now be addressed by https://github.com/conda-forge/ucx-split-feedstock/pull/142/commits/39efc1b8ff1114496f2fbf27370dbd66b83f6720. I'd appreciate if you could take a look/approve that, and once https://github.com/conda-forge/rdma-core-feedstock/pull/9 is merged we can trigger a rebuild and get the UCX updates merged too.

**Comment by kkraus14** [comment]
All of that is correct, but in addition to that I believe we need to ignore the run export from rdma-core via the `ignore_run_exports` (or `ignore_run_exports_from` section: https://docs.conda.io/projects/conda-build/en/stable/resources/define-metadata.html#export-runtime-requirements

Otherwise, I believe you would end up with both the run export constraint and the defined constraint, which when combined yields the same behavior as just the run export constraint.

**Comment by jakirkham** [comment]
Linking this comment here in case it was missed: https://github.com/conda-forge/rdma-core-feedstock/pull/9#discussion_r1355590069

**Comment by pentschev** [comment]
> All of that is correct, but in addition to that I believe we need to ignore the run export from rdma-core via the `ignore_run_exports` (or `ignore_run_exports_from` section: https://docs.conda.io/projects/conda-build/en/stable/resources/define-metadata.html#export-runtime-requirements
> 
> Otherwise, I believe you would end up with both the run export constraint and the defined constraint, which when combined yields the same behavior as just the run export constraint.

Thanks Keith, given we want to ignore only `rdma-core` from `run_exports` -- and if my understanding is correct --, I think the appropriate is to add it to the `ignore_run_exports` and not `ignore_run_exports_from` which would include _all_ `rdma-core`'s `run_exports` (although none other than `rdma-core` itself are currently defined). I've [pushed that change](https://github.com/conda-forge/ucx-split-feedstock/pull/142/commits/1e78eaf356aeb77ee55d8238fefc7a70fda7b4d3), but please feel free to correct or disagree with my understanding if you think `ignore_run_exports_from` would be appropriate.

> Linking this comment here in case it was missed: [conda-forge/rdma-core-feedstock#9 (comment)](https://github.com/conda-forge/rdma-core-feedstock/pull/9#discussion_r1355590069)

Thanks John, I wrote https://github.com/conda-forge/rdma-core-feedstock/pull/9#discussion_r1355678119 with next steps.

**Comment by jakirkham** [comment]
Re-reading the discussion here am wondering whether we can relax `rdma-core`'s `run_exports` pin further. Have written this up in issue: https://github.com/conda-forge/rdma-core-feedstock/issues/12

Would be interested to hear thoughts on that idea

**Comment by pentschev** [comment]
With https://github.com/conda-forge/ucx-split-feedstock/pull/142 now merged, this is complete. Closing.
