### ISSUE TITLE
conda-forge::cuda-version 12.1 support

### ISSUE THREAD

**Issue by elgalu** [conda-forge/ucx-split-feedstock#151]
### Comment:

Currently conda fails with error: ucx 1.15.0 requires cuda-version >=11.2,<12

**Comment by jakirkham** [comment]
Could you please share more info? In particular please fill out the bug report issue template

We also build a CUDA 12 compatible package

https://github.com/conda-forge/ucx-split-feedstock/blob/1c78700bed4f9db63eee2195876ff02ea269fdd7/recipe/meta.yaml#L48

**Comment by jakirkham** [comment]
Closing as no response. If there are still issues, please open a new bug issue with the template filled out. Thanks! 🙏
