### ISSUE TITLE
Use Conda package instead of CDTs for `libnl*`

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/ucx-split-feedstock#159]
Currently we have CDTs for `libnl*` that are used in the `ucx` recipe:

https://github.com/conda-forge/ucx-split-feedstock/blob/1c50eab5ca4bdb8d4d54e5bb11bb34a8fa8f852f/recipe/meta.yaml#L32-L33

Would it be possible to drop these and use the `libnl` package?

**Comment by jakirkham** [comment]
@pentschev could you please help us evaluate if this is an option for us?

**Comment by jakirkham** [comment]
Going to start a PR with these changes. This should help us create some artifacts for testing

**Comment by jakirkham** [comment]
@conda-forge-admin , please re-render

**Comment by pentschev** [comment]
Thanks John!
