### ISSUE TITLE
UCX 1.17

### ISSUE THREAD

**Issue by marcinz** [conda-forge/ucx-split-feedstock#183]
### Comment:

UCX 1.17 has been released, but the conda package is not available yet. How is the package build triggered, and how long does it usually take after a release?

**Comment by marcinz** [comment]
#182  seems to be ready.

**Comment by sbuneti** [comment]
@leofang this is considered a blocker for 24.06 Conda package release, appreciate if you can expedite this task. Thank you

**Comment by jakirkham** [comment]
@marcinz @sbuneti would either of you be interested in helping with the maintenance here? 🙂

**Comment by leofang** [comment]
Based on an offline conversation @marcinz is willing to help. Let's make an update PR and have him do a final confirmation.

**Comment by leofang** [comment]
#188
