### ISSUE TITLE
Building with mlx5 Direct Verbs support

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/ucx-split-feedstock#56]
Currently we are not building with mlx5 Direct Verbs support. This would be useful in scenarios where Mellanox NICs are available as it could give us a performance boost. To do this we would need the following.

1. CDT for `libmlx5`
2. CDT for headers (no `libmlx5-devel` in CentOS 6?)
3. `--with-mlx5-dv` to `./configure`.

Both 1 and 3 seem straightforward (though there may be other issues). It's unclear how to address 2 currently.

**Comment by jakirkham** [comment]
Based on some discussions at the UCF Hackathon, it sounds like we will need to build rdma-core from source to support this functionality.

**Comment by jakirkham** [comment]
Think this will be fixed by PR ( https://github.com/conda-forge/ucx-split-feedstock/pull/125 ) (and have noted that in that PR)

@pentschev , could you please comment on whether that is accurate (or if more is still needed)?

**Comment by pentschev** [comment]
> Think this will be fixed by PR ( #125 ) (and have noted that in that PR)
> 
> @pentschev , could you please comment on whether that is accurate (or if more is still needed)?

This is correct John. Thanks for following up here and noting that in #125 .
