### ISSUE TITLE
Adding `run_exports` to pin `ucx` in downstream dependencies

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/ucx-split-feedstock#88]
Not sure how tightly we need to pin things. To the patch release, minor, or if major version would be safe. Raising this issue to track that discussion and update the package accordingly

**Comment by jakirkham** [comment]
This is relevant for `openmpi`, which would like to depend on this package ( https://github.com/conda-forge/openmpi-feedstock/pull/87#pullrequestreview-627225281 )

**Comment by jakirkham** [comment]
cc @yosefe @pentschev

**Comment by matthiasdiener** [comment]
Looking at https://abi-laboratory.pro/index.php?view=timeline&l=ucx, pinning to the minor version appears to be most appropriate?

**Comment by pentschev** [comment]
Minor UCX versions generally have bug fixes that were discovered after the initial major release. For example, [1.12.1](https://github.com/openucx/ucx/milestone/18) that's due on February 15th contains several critical fixes related to IB+CUDA usage. Therefore, I would highly recommend the latest minor version.

**Comment by pentschev** [comment]
> Looking at https://abi-laboratory.pro/index.php?view=timeline&l=ucx, pinning to the minor version appears to be most appropriate?

I wasn't aware of that project, but it seems that UCX is very outdated there, latest version seems to be 1.8.0 which is almost 2 years old.

**Comment by jakirkham** [comment]
> Minor UCX versions generally have bug fixes that were discovered after the initial major release. For example, [1.12.1](https://github.com/openucx/ucx/milestone/18) that's due on February 15th contains several critical fixes related to IB+CUDA usage. Therefore, I would highly recommend the latest minor version.

Just to clarify minor would be `12` whereas patch would be the final `1`. Think Matthias is suggesting pinning to `1.12.x` and letting `x` go to latest. Is this what you mean as well?

**Comment by jakirkham** [comment]
> > Looking at https://abi-laboratory.pro/index.php?view=timeline&l=ucx, pinning to the minor version appears to be most appropriate?
> 
> I wasn't aware of that project, but it seems that UCX is very outdated there, latest version seems to be 1.8.0 which is almost 2 years old.

This happens sometimes. Raised issue ( https://github.com/lvc/abi-tracker/issues/15 ) on updating it

**Comment by pentschev** [comment]
Yes, you're right @jakirkham , thanks for catching my mistake.

**Comment by matthiasdiener** [comment]
#92 adds run_exports

**Comment by jakirkham** [comment]
The ABI Laboratory page is updated

https://abi-laboratory.pro/index.php?view=timeline&l=ucx
